apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: githubscaffoldingwithcompositionpage-test-04-composition-resources
  namespace: kube-node-lease
spec:
  api:
    - name: pods
      path: "/api/v1/pods"
      verb: GET
  filter: >
    { 
      "items": .pods.items | map([
        {"valueKey": "name", "kind": "jsonSchemaType", "type": "string", "stringValue": .metadata.name},
        {"valueKey": "namespace", "kind": "jsonSchemaType", "type": "string", "stringValue": .metadata.namespace},
        {"valueKey": "status", "kind": "jsonSchemaType", "type": "string", "stringValue": .status.phase}
      ]) 
    }
